stages:
  - install
  - test
  - docker-ci
install support for python:
  image: python:3.11.1-alpine
  stage: install
  script:
  - python --version
installing requirements file and testing:
  image: python:3.11.1-alpine
  stage: test
  script: 
  - python -m venv env
  - source env/bin/activate
  - pip install -r requirements.txt
  - pip freeze

