name: Testing

on:
  push:
    branches:
      - master
      - githubci
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python 3.11
        uses: actions/checkout@v2
        with:
          python-version: 3.11
      - name: Installation actions/checkout
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          pip freeze
      


    